# Emerald Dark Theme

background            #0b0f0e
foreground            #ecf3f2
cursor                #10b981
cursor_text_color     #0b0f0e
selection_background  #063b31
selection_foreground  #ecf3f2

# URL underline color when hovering
url_color             #34d399

# Kitty window border colors
active_border_color     #10b981
inactive_border_color   #063b31
bell_border_color       #fbbf24

# Tab bar colors
active_tab_foreground   #0b0f0e
active_tab_background   #10b981
inactive_tab_foreground #94a3b8
inactive_tab_background #063b31
tab_bar_background      #050707

# THE 16 TERMINAL COLORS

# black
color0  #0b0f0e
color8  #1e293b

# red
color1  #ef4444
color9  #f87171

# green (Emerald)
color2  #10b981
color10 #34d399

# yellow
color3  #f59e0b
color11 #fbbf24

# blue
color4  #3b82f6
color12 #60a5fa

# magenta
color5  #8b5cf6
color13 #a78bfa

# cyan
color6  #06b6d4
color14 #22d3ee

# white
color7  #f1f5f9
color15 #ffffff
selection_background  #063b31
