# Everforest Dark Hard

background            #272e33
foreground            #d3c6aa
cursor                #d3c6aa
cursor_text_color     #2d353b
selection_background  #475258
selection_foreground  #d3c6aa

# URL underline color when hovering
url_color             #7fbbb3

# Kitty window border colors
active_border_color     #a7c080
inactive_border_color   #3d484d
bell_border_color       #e67e80

# Tab bar colors
active_tab_foreground   #272e33
active_tab_background   #a7c080
inactive_tab_foreground #959dcb
inactive_tab_background #343f44
tab_bar_background      #232a2e

# THE 16 TERMINAL COLORS

# black
color0  #414868
color8  #414868

# red
color1  #e67e80
color9  #e67e80

# green
color2  #a7c080
color10 #a7c080

# yellow
color3  #dbbc7f
color11 #dbbc7f

# blue
color4  #7fbbb3
color12 #7fbbb3

# magenta
color5  #d699b6
color13 #d699b6

# cyan
color6  #83c092
color14 #83c092

# white
color7  #d3c6aa
color15 #d3c6aa
