# Oxocarbon for Kitty

background              #161616
foreground              #f2f4f8
cursor                  #f2f4f8
cursor_text_color       #161616
selection_background    #393939
selection_foreground    #f2f4f8

url_color               #3ddbd9

active_border_color     #33b1ff
inactive_border_color   #525252
bell_border_color       #42be65

wayland_titlebar_color  system
macos_titlebar_color    system

active_tab_foreground   #161616
active_tab_background   #33b1ff
inactive_tab_foreground #f2f4f8
inactive_tab_background #393939
tab_bar_background      #0d0d0d

# black
color0 #262626
color8 #525252

# red
color1 #ee5396
color9 #ff7eb6

# green
color2  #42be65
color10 #42be65

# yellow
color3  #ffe97b
color11 #ffe97b

# blue
color4  #33b1ff
color12 #82cfff

# magenta
color5  #be95ff
color13 #d4bbff

# cyan
color6  #3ddbd9
color14 #08bdba

# white
color7  #dde1e7
color15 #f2f4f8
