# Deep Ocean for Kitty
# Azul marinho quase preto com ciano profundo

background              #0b0d12
foreground              #caf0f8
cursor                  #4dc4ff
cursor_text_color       #0b0d12
selection_background    #162030
selection_foreground    #caf0f8

url_color               #00b4d8

active_border_color     #4dc4ff
inactive_border_color   #1e3048
bell_border_color       #90e0ef

wayland_titlebar_color  system
macos_titlebar_color    system

active_tab_foreground   #0b0d12
active_tab_background   #4dc4ff
inactive_tab_foreground #caf0f8
inactive_tab_background #162030
tab_bar_background      #060810

# black
color0 #162030
color8 #1e3048

# red
color1 #e06c75
color9 #f08090

# green
color2  #52d9a0
color10 #70edb8

# yellow
color3  #e5a84e
color11 #f0c070

# blue
color4  #4dc4ff
color12 #80d8ff

# magenta
color5  #7b8cde
color13 #9daaf0

# cyan
color6  #00b4d8
color14 #48cae4

# white
color7  #a8d8ea
color15 #caf0f8
