# Palenight for Kitty
# Material Palenight

background              #292d3e
foreground              #a6accd
cursor                  #c792ea
cursor_text_color       #292d3e
selection_background    #3c415a
selection_foreground    #a6accd

url_color               #89ddff

active_border_color     #c792ea
inactive_border_color   #585e7d
bell_border_color       #ffcb6b

wayland_titlebar_color  system
macos_titlebar_color    system

active_tab_foreground   #292d3e
active_tab_background   #c792ea
inactive_tab_foreground #a6accd
inactive_tab_background #3c415a
tab_bar_background      #1c1f2e

# black
color0 #292d3e
color8 #585e7d

# red
color1 #f07178
color9 #f07178

# green
color2  #c3e88d
color10 #c3e88d

# yellow
color3  #ffcb6b
color11 #ffcb6b

# blue
color4  #82aaff
color12 #82aaff

# magenta
color5  #c792ea
color13 #c792ea

# cyan
color6  #89ddff
color14 #89ddff

# white
color7  #a6accd
color15 #ffffff
