# Obsidian for Kitty
# Roxo-preto mineral com índigo e lavanda fria

background              #070710
foreground              #e8e8ff
cursor                  #7070ff
cursor_text_color       #070710
selection_background    #16163a
selection_foreground    #e8e8ff

url_color               #60d0ff

active_border_color     #7070ff
inactive_border_color   #252555
bell_border_color       #a0a0ff

wayland_titlebar_color  system
macos_titlebar_color    system

active_tab_foreground   #070710
active_tab_background   #7070ff
inactive_tab_foreground #e8e8ff
inactive_tab_background #16163a
tab_bar_background      #030308

# black
color0 #16163a
color8 #252555

# red
color1 #ff6080
color9 #ff80a0

# green
color2  #60ffb0
color10 #80ffc0

# yellow
color3  #d4d4ff
color11 #e8e8ff

# blue
color4  #7070ff
color12 #9090ff

# magenta
color5  #a0a0ff
color13 #c0c0ff

# cyan
color6  #60d0ff
color14 #80e0ff

# white
color7  #c8c8ff
color15 #e8e8ff
