# Midnight Carbon for Kitty
# Preto puro + azul elétrico + verde terminal

background              #080808
foreground              #c9d1d9
cursor                  #58a6ff
cursor_text_color       #080808
selection_background    #1c1c1c
selection_foreground    #c9d1d9

url_color               #39d0d8

active_border_color     #58a6ff
inactive_border_color   #2d2d2d
bell_border_color       #e3b341

wayland_titlebar_color  system
macos_titlebar_color    system

active_tab_foreground   #080808
active_tab_background   #58a6ff
inactive_tab_foreground #c9d1d9
inactive_tab_background #1c1c1c
tab_bar_background      #040404

# black
color0 #1c1c1c
color8 #484f58

# red
color1 #ff5555
color9 #ff7777

# green
color2  #3fb950
color10 #56d364

# yellow
color3  #e3b341
color11 #f0c94f

# blue
color4  #58a6ff
color12 #79b8ff

# magenta
color5  #bc8cff
color13 #d2a8ff

# cyan
color6  #39d0d8
color14 #56d4dd

# white
color7  #b1bac4
color15 #c9d1d9
