# Nebula for Kitty
# Preto absoluto + magenta neon + ciano estelar

background              #0a0010
foreground              #e8d5ff
cursor                  #ff2dce
cursor_text_color       #0a0010
selection_background    #1e0040
selection_foreground    #e8d5ff

url_color               #30d5c8

active_border_color     #ff2dce
inactive_border_color   #3a1060
bell_border_color       #bf5af2

wayland_titlebar_color  system
macos_titlebar_color    system

active_tab_foreground   #0a0010
active_tab_background   #ff2dce
inactive_tab_foreground #e8d5ff
inactive_tab_background #1e0040
tab_bar_background      #040008

# black
color0 #1e0040
color8 #3a1060

# red
color1 #ff2dce
color9 #ff6ef7

# green
color2  #30d5c8
color10 #00f5e0

# yellow
color3  #d4aaff
color11 #e8d5ff

# blue
color4  #bf5af2
color12 #9d70ff

# magenta
color5  #ff2dce
color13 #ff6ef7

# cyan
color6  #30d5c8
color14 #00f5e0

# white
color7  #c8b0e8
color15 #e8d5ff
